### ISSUE TITLE
Port to QT5?

### ISSUE THREAD

**Issue by alexws54tk** [EvgenijM86/emercoin#3]
People (or at least KDE) are moving to QT5, so emercoin should too! :)
Maybe it's a little too early for this though.

Kubuntu 15.04 and 15.10 has KDE5 as default. And fedora is going to have it as well in May release.

With Qt5 your ui is going to be faster on linux because Qt5 uses xcb protocol to communicate with X11, and besides Qt5 supports Wayland, a modern OpenGL-based replacement of X11 (Fedora will ship an experimental Wayland session).

**Comment by EvgenijM86** [comment]
We are currently working on "merge" branch. It merges emercoin with bitcoin 0.10.2. In bitcoin 0.10.2 you can specify ./configure --with-gui=qt5.  (have not tested it yet in our branch)
